### ISSUE TITLE
Possible to initialize using HTML markup?

### ISSUE THREAD

**Issue by veer-os** [RobertoPrevato/jQuery-KingTable#10]
Does it support initializing from HTML markup of table. This will make it really cool.

**Comment by RobertoPrevato** [comment]
Hi @veer-os, unfortunately my library does not support configuration by HTML markup. I am not dedicating more time to this exact repository, since I prefer to work on the new version of the library [(here in GitHub, KingTable)](https://github.com/RobertoPrevato/KingTable). The new version is improved in many ways, and independent from jQuery and Lodash. I could add there this option, your advice is really good.
