### ISSUE TITLE
Basic code not working?!

### ISSUE THREAD

**Issue by vlatro** [RobertoPrevato/jQuery-KingTable#5]
I'm trying for hours to run the code for KingTable.

I think there must be a problem with the code, as I even don't see anything working when I try to use your example file(s):

This is my pad (not accessible for you)
http://intranetbe:85/cis/js/jQuery-KingTable-master/source/

And this is what I get (empty screen) :-(
![image](https://cloud.githubusercontent.com/assets/24847194/21572887/b6b484f2-cede-11e6-99bc-7cb5fba02efe.png)

Please help ?!

**Comment by RobertoPrevato** [comment]
Hi @vlatro, are you running a development server using Python Flask, like described [here in the Readme file](https://github.com/RobertoPrevato/jQuery-KingTable#how-to-run-the-provided-development-server)?

A development server is required, and I needed one for development, since some features require server side pagination, sorting and filtering (since filtering and sorting affect pagination). I chose Python Flask because it's a lightweight and convenient web framework. If you want, I can help setting up the development environment with Python Flask.

If instead you desire example files that do not require a running web server, please download those from the [demo, here](http://ugrose.com/content/demos/kingtable/index.html).
This demo works using only static files and does pagination and filtering on the client side: they are fixed tables. I described what I mean by "fixed table" [here in the wiki](https://github.com/RobertoPrevato/jQuery-KingTable/wiki/Working-modes#fixed-mode).

**Comment by vlatro** [comment]
Hi Roberto,

Thank you for the answer! 

I don't have a development server using Python Flask, so I want to try tu use the 'static' version.

I just copied some of the code from the demo, but it's still not working.
Please find my file attached.
[test.zip](https://github.com/RobertoPrevato/jQuery-KingTable/files/680542/test.zip)

I hope I'm not asking stupid questions. I'm pretty new with jQuery.

Thanks
Gert

**Comment by RobertoPrevato** [comment]
Hi Gert,
Don't worry, you're not asking stupid questions. This aspect of my repository was not enough documented. I just added better documentation on how to run the development server included in the repository.

I am observing the file you sent me, and it couldn't work because it expects a list of objects (in a global variable called **COLORS**, which you are not loading, because you don't have the <script> tag pointing to the file that contains the declaration of this object. The file containing the list of colors in my demo is here: [http://ugrose.com/content/demos/kingtable/scripts/data.js](http://ugrose.com/content/demos/kingtable/scripts/data.js).

 This thing works fine for a demo, but in real applications you would fetch data from the server side. In your case, most probably you want to either:
* load an array of objects using an AJAX request, then pass this array of items to the KingTable constructor - in this case my JavaScript code offers pagination, search and sorting out of the box - but of course this is fine only for small tables that do not require server side pagination (e.g. tables that never grows to more than 500 items) - 
* implement the server side method that returns a paginated list of items, and edit the parameters of the KingTable constructor to use the URL of this method (instead of a static list of items) - this point is described in the wiki [Working Modes - normal mode](https://github.com/RobertoPrevato/jQuery-KingTable/wiki/Working-modes#normal-mode) and [How to integrate with server side code](https://github.com/RobertoPrevato/jQuery-KingTable/wiki/How-to-integrate-with-your-project#how-to-integrate-with-server-side-code)

As a side note, I give you an advice: if you open the browser developer's tools (e.g. CTRL + LSHIFT + i in Google Chrome), the _Console_ tab would show you what is the problem: in your case it should say something about COLORS being undefined.

In any case, I recommend you to try to run the development server using Python Flask: it's really easy and it will help understanding how AJAX requests work in fetching data that require server side pagination for my table plugin. I added a [detailed description to the Readme file, on how to create the development environment in Python](https://github.com/RobertoPrevato/jQuery-KingTable/#how-to-run-the-provided-development-server).

Please let me know if this helps.

Roberto

**Comment by RobertoPrevato** [comment]
@vlatro, I also noticed that dependencies are not loaded in the right order:
since jquery.kingtable.min.js requires Lodash and r.js; it should be loaded after these other two libraries. JavaScript code is evaluated in the same order of _script_ elements.

**Comment by vlatro** [comment]
Dear Roberto,

I'm using this script at my work, and I do not have the possiblity to
install something on the server.
I would use the AJAX-option to get data from my SQL database.

I just changed everything you said before (order of dependencies, colors
file,...) and this does not seems to help.

Here are the "console" errors:

![image](https://cloud.githubusercontent.com/assets/24847194/21589045/def52140-d0ed-11e6-8200-2d7117a9411d.png)

​

Thanks
Gert


2017-01-02 11:11 GMT+01:00 Roberto Prevato <notifications@github.com>:

**Comment by RobertoPrevato** [comment]
Dear Gert,
I understand your situation: I work in financial services and also cannot install applications freely on work servers.

The first error in the console is described by the error message itself: the link provided by the error message describes the details: [https://github.com/RobertoPrevato/jQuery-KingTable/wiki/Implementing-localization](https://github.com/RobertoPrevato/jQuery-KingTable/wiki/Implementing-localization). The KingTable library requires something to provide client side localization (I don't like those libraries that hard code texts in English inside their source code, making the assumption that every website must be in English - like for example chosen.js), so I throw exception if an implementation of i18n is missing.

The solution is to include a library for client side localization: in my demo page you can see in the html
```html
  <!-- utility function for localization -->
  <script src="scripts/libs/i.js"></script>
  <script src="scripts/areas/public/locale/en.js"></script>
  <script src="scripts/areas/public/locale/it.js"></script>
  <script src="scripts/areas/public/locale/pl.js"></script>
```
Once this error is resolved, the second should be resolved automatically, too, since $.KingTable gets defined. You still need the COLORS data to feed the KingTable function.

**Comment by vlatro** [comment]
I've added i.js to my asp file, together with the en.js, it.js and pl.js.
Now the error message has changed to:


![image](https://cloud.githubusercontent.com/assets/24847194/21590741/b054b6be-d0fe-11e6-9d7b-fc7126333b4b.png)

**Comment by vlatro** [comment]
The COLORS data is already included, see attechment
[test.zip](https://github.com/RobertoPrevato/jQuery-KingTable/files/680887/test.zip)

**Comment by RobertoPrevato** [comment]
@vlatro, once again: JavaScripts are evaluated in the same order of script elements (this is how browsers work), so i.js must be loaded before the tables plugin.

The exception thrown by jquery.kingtable.min.js is telling you that i18n is still missing (when the code is evaluated); the solution is to load the depedency _before_ this library:

```html
<!------- KINGTABLE -------->
<script src="js/jQuery-KingTable-master/dist/lodash.js"></script>
<script src="js/r.js"></script>
<!-- utility function for localization -->
<script src="js/i.js"></script>
<script src="js/en.js"></script>
<script src="js/it.js"></script>
<script src="js/pl.js"></script>

<!-- all dependencies are loaded before, so they exist when KingTable is defined: -->
<script src="js/jQuery-KingTable-master/dist/jquery.kingtable.min.js"></script>
<script src="http://ugrose.com/content/demos/kingtable/scripts/data.js"></script>

```
Some people find this behavior of JavaScript annoying, so they developed different solutions to this problem (they want to be able to load JavaScript in sparse order), such as RequireJs. However, plain vanilla JavaScript still works this way, by default.

**Comment by vlatro** [comment]
OK thanks (feeling dumb)

I modified that and now all the errors are gone.

But my file is still showing a white screen :-(

[test.zip](https://github.com/RobertoPrevato/jQuery-KingTable/files/681009/test.zip)

**Comment by RobertoPrevato** [comment]
Hi Gert,
I think there is a single last mistake: your script tag appears before the **body** element, hence when the function is executed, the element with id "content" is not in the DOM, yet.

jQuery fails silently, because $("#content") is an empty array and jQuery doesn't see anything wrong with it.

You should either use the jQuery $( document ).ready() function, so modify this way:
```html
  <script>
    $(document).ready(function () {
      // ... table initialization here
    });
  </script>
```

Or, move the script elements all together before the closing **</body>** tag. In my opinion, having the script elements before the closing of the body is a best practice, but this is subjective.

**Comment by vlatro** [comment]
Hi Roberto.

Thank you so much for the help. I can image you have better things to do :-).

![image](https://cloud.githubusercontent.com/assets/24847194/21601773/f5285e00-d18d-11e6-9b75-3f73ada8d52e.png)

Seems to be working fine now, except for the icons.

![image](https://cloud.githubusercontent.com/assets/24847194/21601685/28d968bc-d18d-11e6-812e-5d980cb57d06.png)

I assume the reason is that the jquery.Kingtable.js can't find the needed "open-iconic" files.
For the moment I added the script like this:
<script src="js/jQuery-KingTable-master/dist/jquery.kingtable.js"></script>

I thought the error would be resolved when I used this location:
<script src="js/jQuery-KingTable-master/source/scripts/libs/kingtable/jquery.kingtable.js"></script>

But if I do that, i get another (worse) error.
![image](https://cloud.githubusercontent.com/assets/24847194/21601744/bafd087a-d18d-11e6-989a-551ac5a13b3e.png)

**Comment by RobertoPrevato** [comment]
Hi Gert,
No problem, you asked kindly and that's why I help :)

So, when you have a problem fetching fonts, you should take a look at CSS: fonts are usually fetched due to some CSS "font-face" rule and JavaScript is not involved. I can see from the browser log that it's looking for open-iconic fonts in this place:
``
~/styles/openicon/fonts/open-iconic.woff
``
Where ~ represents the root of your web application (the same folder where you should have your main **Web.config** file), and it's not finding them. Maybe you've got a different folder structure, like:
``
~/js/jQuery-KingTable-master/source/styles/openicon/fonts/open-iconic.woff
``
I am guessing.

So, the solution is either to recreate the folder structure expected by the CSS rules (i.e. create ~/styles/openicon/fonts/open-iconic.woff), or modify the CSS rules to follow your desired folder structure.

In the second case, you could edit the CSS I wrote, for example replacing inside the KingTable css file:
```css
@font-face {
  font-family:Icons; 
  src:url(/styles/openicon/fonts/open-iconic.eot); 
  src:url(/styles/openicon/fonts/open-iconic.eot?#iconic-sm)
```
With:
```css
@font-face {
  font-family:Icons; 
  src:url(/your/desired/path_to_fonts/open-iconic.eot); 
  src:url(/your/desired/path_to_fonts/open-iconic.eot?#iconic-sm)
```

[Edit] Or, override these CSS rules, creating another .css file that you load after the KingTable css, containing a fragment like this one:
```css
@font-face {
  font-family: 'Icons';
  src: url('/your/desired/path_to_fonts/open-iconic.eot');
  src: url('/your/desired/path_to_fonts/open-iconic.eot?#iconic-sm') format('embedded-opentype'), url('/your/desired/path_to_fonts/open-iconic.woff') format('woff'), url('/your/desired/path_to_fonts/open-iconic.ttf') format('truetype'), url('/your/desired/path_to_fonts/open-iconic.otf') format('opentype'), url('/your/desired/path_to_fonts/open-iconic.svg#iconic-sm') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

If you want to work comfortably with the source code (I mean, editing LESS code) you should: install NodeJs and Grunt in a development machine (one where you can install software freely), edit my LESS source code and use the provided gruntfile to generate CSS from LESS source code.
